apiVersion: v1
kind: Secret
metadata:
  name: wordpress-db-secrets
  namespace: default
type: Opaque
stringData:
  WORDPRESS_DB_HOST: mysql-woo-enterprise-prod.mysql.database.azure.com
  WORDPRESS_DB_USER: woo_admin
  WORDPRESS_DB_PASSWORD: "MySQLSecurePassword2026!#"
  WORDPRESS_DB_NAME: wordpress_db
