apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: default
  labels:
    app: wordpress
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: wordpress:latest
          ports:
            - containerPort: 80
              name: http
          env:
            - name: WORDPRESS_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: wordpress-db-secrets
                  key: WORDPRESS_DB_HOST
            - name: WORDPRESS_DB_USER
              valueFrom:
                secretKeyRef:
                  name: wordpress-db-secrets
                  key: WORDPRESS_DB_USER
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wordpress-db-secrets
                  key: WORDPRESS_DB_PASSWORD
            - name: WORDPRESS_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: wordpress-db-secrets
                  key: WORDPRESS_DB_NAME
            - name: WORDPRESS_CONFIG_EXTRA
              value: |
                define('MYSQL_CLIENT_FLAGS', MYSQLI_CLIENT_SSL);
                if (isset($_SERVER['HTTP_HOST'])) {
                    define('WP_HOME', 'http://' . $_SERVER['HTTP_HOST']);
                    define('WP_SITEURL', 'http://' . $_SERVER['HTTP_HOST']);
                }
            # Usar la IP del pod para la instalación interna
            - name: WORDPRESS_HOST
              value: "localhost"
          volumeMounts:
            - name: wordpress-persistent-storage
              mountPath: /var/www/html
            - name: init-script
              mountPath: /docker-entrypoint-initwp.d
          lifecycle:
            postStart:
              exec:
                command: ["/bin/bash", "-c", "bash /docker-entrypoint-initwp.d/install-woocommerce.sh"]
      volumes:
        - name: wordpress-persistent-storage
          persistentVolumeClaim:
            claimName: wordpress-pvc
        - name: init-script
          configMap:
            name: wordpress-init-script
            defaultMode: 0755
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: default
  labels:
    app: wordpress
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: wordpress
  type: LoadBalancer
